---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-deployment
  labels:
    app: project2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project2
  template:
    metadata:
      labels:
        app: project2
    spec:
      containers:
<<<<<<< HEAD
        - image: keoffor/project2:%TAG%
=======
        - image: keoffor/project-2:%TAG%
>>>>>>> 2ec0c5243b963155c166dbbd503639e351d0f090
          imagePullPolicy: Always
          name: project2
          ports:
            - containerPort: 8080
<<<<<<< HEAD
          livenessProbe:
            httpGet:
              path: /hw
              port: 8080
          readinessProbe:
            httpGet:
              path: /hw
              port: 8080
=======

>>>>>>> 2ec0c5243b963155c166dbbd503639e351d0f090
---
apiVersion: v1
kind: Service
metadata:
  name: project2-service
spec:
  selector:
    app: project2
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  defaultBackend:
    service:
<<<<<<< HEAD
      name: project-service
      port:
        number: 8080
=======
      name: project2-service
      port:
        number: 8080
>>>>>>> 2ec0c5243b963155c166dbbd503639e351d0f090
